version: '3'
services:
  demo-app:
    image: blog-demo
    ports:
      - 8080:8080
    depends_on:
      - zookeeper
      - kafka
      - kafka1
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.124
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_LEADER_REBALANCE_ENABLE: 'true'
    depends_on:
      - zookeeper
  kafka1:
      image: wurstmeister/kafka
      ports:
        - "9093:9093"
      environment:
        KAFKA_BROKER_ID: 2
        KAFKA_PORT: 9093
        KAFKA_ADVERTISED_PORT: 9093
        KAFKA_ADVERTISED_HOST_NAME: 192.168.1.124
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_AUTO_LEADER_REBALANCE_ENABLE: 'true'
      depends_on:
        - zookeeper
        - kafka
